version: '3'

services:
  backend:
    image: node:14
    working_dir: /app
    volumes:
      - ./backend:/app
    command: >
      sh -c "
        if [ ! -d /app/.git ]; then
          git clone https://github.com/tu-usuario/tu-repo-backend.git /app
        else
          cd /app && git pull
        fi &&
        npm install && npm start
      "
    environment:
      - DATABASE_URL=mysql://root:rootpassword@db:3306/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    image: node:14
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: >
      sh -c "
        if [ ! -d /app/.git ]; then
          git clone https://github.com/tu-usuario/tu-repo-frontend.git /app
        else
          cd /app && git pull
        fi &&
        npm install &&
        export REACT_APP_BACKEND_URL=$${REACT_APP_BACKEND_URL:-http://localhost:3000} &&
        npm start
      "
    environment:
      - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL:-http://localhost:3000}
    ports:
      - "80:3000"
    depends_on:
      - backend

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myapp
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

networks:
  default:
    driver: bridge

volumes:
  mysql-init:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./mysql-init